theme = "tokyonight_storm"

[editor]
true-color = true
rulers = [79,88]
line-number = "relative"
mouse = true
bufferline = "multiple"
shell = ["zsh", "-c"]
cursorline = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"
# or control each character
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "-" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
