[[language]]
name = "python"
rulers = [88]
auto-format = true
formatter = {command = "bash", args = ["-c", "isort --profile black - | black --quiet -"]} 

[language-server.pylsp.config]
configurationSources = ["pyproject.toml", "setup.cfg"]

[language-server.pylsp.config.plugins]
pycodestyle.enabled = false
pyflakes.enabled = false
yapf.enabled = false
pylint.enabled = true
args = ["--rcfile=pyproject.toml", "--rcfile=setup.cfg"]
flake8.enabled = true

[[language]]
name = "hcl"
file-types = ["tf"]
auto-format = true
formatter = { command = "terraform fmt %f" , args = ["--stdin"] }


[[language]]
name = 'toml'
