[[language]]
name = "python"
rulers = [79,88]
auto-format = true
formatter = {command = "bash", args = ["-c", "isort --profile black - | black --quiet --line-length=88 -"]} 

[language.config.pylsp]
configurationSources = ["pyproject.toml", "setup.cfg"]
plugins.pycodestyle.enabled = false
plugins.pyflakes.enabled = false
plugins.yapf.enabled = false

[language.config.pylsp.plugins.pylint]
enabled = true
args = ["--rcfile=pyproject.toml", "--rcfile=setup.cfg"]

[language.config.pylsp.plugins.flake8]
enabled = true

[[language]]
name = "hcl"
file-types = ["tf"]
auto-format = true
formatter = { command = "terraform fmt %f" , args = ["--stdin"] }


[[language]]
name = 'toml'
config = {}
