config_version = 2

[audio]
enable_sounds = true

[backdrop]
blur_intensity = 0.669999985024333
tint_intensity = 0.37999999150633812

[bar.default]
capsule_thickness = 0.80000000000000004
center = [ "launcher", "spacer__", "spacer__", "workspaces", "spacer__", "group:g5" ]
end = [ "spacer__", "group:g2", "spacer__", "group:g1", "spacer__", "group:g4", "spacer__", "notifications", "session" ]
margin_ends = 15
padding = 10
scale = 1.25
start = [ "control-center", "group:g3" ]

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "weather", "clock", "date" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "network", "bluetooth", "tray" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "settings", "wallhaven", "screenshot", "clipboard" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "volume", "brightness", "battery" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g5"
    members = [ "media", "audio_visualizer" ]
    opacity = 1.0
    padding = 6.0

[battery]
warning_threshold = 15

    [battery.device."/org/freedesktop/UPower/devices/bluetooth_generic_dev_78_C1_1D_46_93_B4"]
    warning_threshold = 15

    [battery.device."/org/freedesktop/UPower/devices/headset_dev_78_C1_1D_46_93_B4"]
    warning_threshold = 15

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

[control_center]
sidebar_section = "none"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1536.0
    cy = 1609.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[nightlight]
enabled = true

[osd]
scale = 1.1500000096857548

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder", "noctalia/wallhaven" ]

[shell]
corner_radius_scale = 1.1500000171363354
lang = "en"
niri_overview_type_to_launch_enabled = true
password_style = "random"
settings_show_advanced = true
telemetry_enabled = true
ui_scale = 1.1500000096857548

    [shell.launcher]
    app_grid = true
    session_search = true

    [shell.panel]
    control_center_position = "top_right"
    launcher_placement = "attached"
    launcher_position = "auto"
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 15

[theme]
builtin = "Tokyo-Night"
community_palette = "ADW"
custom_palette = "wallhaven-2em38y-fs"
source = "community"

    [theme.templates]
    builtin_ids = [ "ghostty", "niri", "starship" ]
    community_ids = [ "pi-agent", "zen-browser", "neovim", "vscode", "zed", "rofi", "steam", "yazi" ]

[wallpaper]
fill_mode = "fit"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/a_merii/Pictures/Wallpapers/wallhaven-9mjoy1.png"

    [wallpaper.last]
    path = "/home/a_merii/Pictures/Wallpapers/wallhaven-9mjoy1.png"

    [wallpaper.monitors.DP-1]
    path = "/home/a_merii/Pictures/Wallpapers/wallhaven-9mjoy1.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/a_merii/Pictures/Wallpapers/wallhaven-9mjoy1.png"

[widget.active_window]
capsule_padding = 7.0
display = "icon_only"
icon_size = 20.0

[widget.battery]
capsule = true
hide_when_full = true

[widget.bluetooth]
capsule = true

[widget.brightness]
capsule = true
color = "#CEBE3B"

[widget.cat]
audio_spectrum = true
capsule = true
color = "#025C61"
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clipboard]
capsule = true
color = "#FFB000"

[widget.clock]
capsule = true
capsule_foreground = "on_surface_variant"
format = "{:%l:%M %p}"

[widget.control-center]
capsule = true
capsule_foreground = "primary"
capsule_opacity = 0.84999999999999998
capsule_padding = 5.0
glyph = "navigation-filled"
scale = 1.5

[widget.date]
capsule = true
capsule_foreground = "on_surface_variant"

[widget.launcher]
scale = 1.5

[widget.media]
capsule = true
capsule_foreground = "outline"
color = "secondary"
hide_when_no_media = true
title_scroll = "always"

[widget.network]
capsule = true
color = "#ADCFF8"
show_label = false

[widget.notifications]
color = "#E9BF3D"
scale = 1.1500000000000001

[widget.power_profile]
color = "#006021"

[widget.screenshot]
color = "#6394C2"

[widget.session]
capsule_foreground = "error"
color = "error"
scale = 1.1000000000000001

[widget.spacer__]
length = 10
type = "spacer"

[widget.tray]
capsule = true
drawer = true

[widget.volume]
capsule = true
color = "tertiary"

[widget.wallhaven]
color = "#E987EB"
type = "noctalia/wallhaven:wallhaven"