HISTSIZE=1000000
SAVEHIST=1000000
export EDITOR=$HOME/.cargo/bin/hx
export SUDOEDITOR=$HOME/.cargo/bin/hx
export VISUAL=$HOME/.cargo/bin/hx
export PATH=$HOME/.local/bin:$PATH
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$PATH:$GOPATH/bin
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export ZDOTDIR=$HOME/.config/zsh
